// Code generated by scripts/generate_go_sdk.py; DO NOT EDIT.
package xdk

import "context"

type ChatClient struct {
	client *Client
}

func (c *ChatClient) MediaUploadFinalize(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.media_upload_finalize"], cloneParams(input))
}

func (c *ChatClient) SendTypingIndicator(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.send_typing_indicator"], cloneParams(input))
}

func (c *ChatClient) GetConversation(input Params) *Pager {
	return c.client.newPager(operations["chat.get_conversation"], cloneParams(input))
}

func (c *ChatClient) MediaDownload(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.media_download"], cloneParams(input))
}

func (c *ChatClient) MediaUploadAppend(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.media_upload_append"], cloneParams(input))
}

func (c *ChatClient) SendMessage(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.send_message"], cloneParams(input))
}

func (c *ChatClient) MarkConversationRead(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.mark_conversation_read"], cloneParams(input))
}

func (c *ChatClient) GetConversations(input Params) *Pager {
	return c.client.newPager(operations["chat.get_conversations"], cloneParams(input))
}

func (c *ChatClient) MediaUploadInitialize(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.media_upload_initialize"], cloneParams(input))
}

func (c *ChatClient) GetUserPublicKeys(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.get_user_public_keys"], cloneParams(input))
}

func (c *ChatClient) AddUserPublicKey(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["chat.add_user_public_key"], cloneParams(input))
}

