// Code generated by scripts/generate_go_sdk.py; DO NOT EDIT.
package xdk

import "context"

type ComplianceClient struct {
	client *Client
}

func (c *ComplianceClient) GetJobs(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["compliance.get_jobs"], cloneParams(input))
}

func (c *ComplianceClient) CreateJobs(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["compliance.create_jobs"], cloneParams(input))
}

func (c *ComplianceClient) GetJobsById(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["compliance.get_jobs_by_id"], cloneParams(input))
}

