// Code generated by scripts/generate_go_sdk.py; DO NOT EDIT.
package xdk

import "context"

type ConnectionsClient struct {
	client *Client
}

func (c *ConnectionsClient) DeleteAll(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["connections.delete_all"], cloneParams(input))
}
