// Code generated by scripts/generate_go_sdk.py; DO NOT EDIT.
package xdk

import "context"

type GeneralClient struct {
	client *Client
}

func (c *GeneralClient) GetOpenApiSpec(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["general.get_open_api_spec"], cloneParams(input))
}

