// Code generated by scripts/generate_go_sdk.py; DO NOT EDIT.
package xdk

import "context"

type NewsClient struct {
	client *Client
}

func (c *NewsClient) Get(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["news.get"], cloneParams(input))
}

func (c *NewsClient) Search(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["news.search"], cloneParams(input))
}
