// Code generated by scripts/generate_go_sdk.py; DO NOT EDIT.
package xdk

var generatedTags = []string{
	"account_activity",
	"activity",
	"communities",
	"community_notes",
	"compliance",
	"connections",
	"direct_messages",
	"general",
	"lists",
	"media",
	"news",
	"posts",
	"spaces",
	"stream",
	"trends",
	"usage",
	"users",
	"webhooks",
}
