// Code generated by scripts/generate_go_sdk.py; DO NOT EDIT.
package xdk

import "context"

type UsageClient struct {
	client *Client
}

func (c *UsageClient) Get(ctx context.Context, input Params) (JSON, error) {
	return c.client.call(ctx, operations["usage.get"], cloneParams(input))
}

